global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node1-exporter:9100'
          # - 'node2-exporter:9100'
          - 'localhost:9090'