global:
  scrape_interval: 30s
  scrape_timeout: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node1-exporter:9100'
          # - 'node2-exporter:9100'
          - 'prometheus:9090'
          - 'idonotexists:564'