version: '3'

services:
  prometheus:
    container_name: node-prom 
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    # volumes:
      #- ./prometheus:/etc/prometheus
      #- prometheus-data:/prometheus
    depends_on:
      - apache
      - grafana

  apache:
    container_name: apache
    build: .
    ports:
      - 8080:80

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
