global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'practica1-exporter-1:9100'
          - 'practica1-exporter-2:9100'
          - 'localhost:9090'